/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

/**
 *
 * @author lpjad
 */
public class DesignCalculator extends javax.swing.JFrame {

    /**
     * Creates new form DesignCalculator
     */
    public DesignCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonSeven = new javax.swing.JButton();
        buttonEight = new javax.swing.JButton();
        buttonNine = new javax.swing.JButton();
        opDivide = new javax.swing.JButton();
        buttonFour = new javax.swing.JButton();
        buttonOne = new javax.swing.JButton();
        opOutput = new javax.swing.JButton();
        buttonFive = new javax.swing.JButton();
        buttonTwo = new javax.swing.JButton();
        buttonZero = new javax.swing.JButton();
        buttonSix = new javax.swing.JButton();
        buttonThree = new javax.swing.JButton();
        opPower = new javax.swing.JButton();
        opMultiply = new javax.swing.JButton();
        opSubstract = new javax.swing.JButton();
        opAdd = new javax.swing.JButton();
        displayResult = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(20, 26, 34));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        buttonSeven.setBackground(new java.awt.Color(25, 16, 9));
        buttonSeven.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        buttonSeven.setForeground(new java.awt.Color(225, 186, 197));
        buttonSeven.setText("7");
        buttonSeven.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSevenActionPerformed(evt);
            }
        });

        buttonEight.setBackground(new java.awt.Color(25, 16, 9));
        buttonEight.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        buttonEight.setForeground(new java.awt.Color(225, 186, 197));
        buttonEight.setText("8");
        buttonEight.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEightActionPerformed(evt);
            }
        });

        buttonNine.setBackground(new java.awt.Color(25, 16, 9));
        buttonNine.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        buttonNine.setForeground(new java.awt.Color(225, 186, 197));
        buttonNine.setText("9");
        buttonNine.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNineActionPerformed(evt);
            }
        });

        opDivide.setBackground(new java.awt.Color(25, 16, 9));
        opDivide.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        opDivide.setForeground(new java.awt.Color(225, 186, 197));
        opDivide.setText("/");
        opDivide.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        opDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opDivideActionPerformed(evt);
            }
        });

        buttonFour.setBackground(new java.awt.Color(25, 16, 9));
        buttonFour.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        buttonFour.setForeground(new java.awt.Color(225, 186, 197));
        buttonFour.setText("4");
        buttonFour.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFourActionPerformed(evt);
            }
        });

        buttonOne.setBackground(new java.awt.Color(25, 16, 9));
        buttonOne.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        buttonOne.setForeground(new java.awt.Color(225, 186, 197));
        buttonOne.setText("1");
        buttonOne.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOneActionPerformed(evt);
            }
        });

        opOutput.setBackground(new java.awt.Color(99, 95, 45));
        opOutput.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        opOutput.setForeground(new java.awt.Color(255, 255, 255));
        opOutput.setText("=");
        opOutput.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        opOutput.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        opOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opOutputActionPerformed(evt);
            }
        });

        buttonFive.setBackground(new java.awt.Color(25, 16, 9));
        buttonFive.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        buttonFive.setForeground(new java.awt.Color(225, 186, 197));
        buttonFive.setText("5");
        buttonFive.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFiveActionPerformed(evt);
            }
        });

        buttonTwo.setBackground(new java.awt.Color(25, 16, 9));
        buttonTwo.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        buttonTwo.setForeground(new java.awt.Color(225, 186, 197));
        buttonTwo.setText("2");
        buttonTwo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTwoActionPerformed(evt);
            }
        });

        buttonZero.setBackground(new java.awt.Color(25, 16, 9));
        buttonZero.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        buttonZero.setForeground(new java.awt.Color(225, 186, 197));
        buttonZero.setText("0");
        buttonZero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZeroActionPerformed(evt);
            }
        });

        buttonSix.setBackground(new java.awt.Color(25, 16, 9));
        buttonSix.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        buttonSix.setForeground(new java.awt.Color(225, 186, 197));
        buttonSix.setText("6");
        buttonSix.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSixActionPerformed(evt);
            }
        });

        buttonThree.setBackground(new java.awt.Color(25, 16, 9));
        buttonThree.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        buttonThree.setForeground(new java.awt.Color(225, 186, 197));
        buttonThree.setText("3");
        buttonThree.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThreeActionPerformed(evt);
            }
        });

        opPower.setBackground(new java.awt.Color(25, 16, 9));
        opPower.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        opPower.setForeground(new java.awt.Color(225, 186, 197));
        opPower.setText("^");
        opPower.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        opPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opPowerActionPerformed(evt);
            }
        });

        opMultiply.setBackground(new java.awt.Color(25, 16, 9));
        opMultiply.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        opMultiply.setForeground(new java.awt.Color(225, 186, 197));
        opMultiply.setText("*");
        opMultiply.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        opMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opMultiplyActionPerformed(evt);
            }
        });

        opSubstract.setBackground(new java.awt.Color(25, 16, 9));
        opSubstract.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        opSubstract.setForeground(new java.awt.Color(225, 186, 197));
        opSubstract.setText("-");
        opSubstract.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        opSubstract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opSubstractActionPerformed(evt);
            }
        });

        opAdd.setBackground(new java.awt.Color(25, 16, 9));
        opAdd.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        opAdd.setForeground(new java.awt.Color(225, 186, 197));
        opAdd.setText("+");
        opAdd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        opAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opAddActionPerformed(evt);
            }
        });

        displayResult.setBackground(new java.awt.Color(25, 16, 19));
        displayResult.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        displayResult.setForeground(new java.awt.Color(225, 186, 197));
        displayResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        displayResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayResultActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(177, 67, 60));
        clear.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(displayResult)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(opOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(buttonZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(buttonOne, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(buttonTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(buttonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(buttonFive, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(buttonSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(buttonEight, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(buttonNine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonSix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonThree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(opPower, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(opDivide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(opMultiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(opSubstract, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(opAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(displayResult, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEight, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNine, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFive, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSix, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOne, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonThree, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opSubstract, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(opOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonZero, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(opPower, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(opAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEightActionPerformed
        // TODO add your handling code here:
        screenText += 8;
        displayResult.setText(screenText);
    }//GEN-LAST:event_buttonEightActionPerformed

    private void opDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opDivideActionPerformed
        // TODO add your handling code here:
        screenText += "/";
        displayResult.setText(screenText);
    }//GEN-LAST:event_opDivideActionPerformed

    private void buttonFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFourActionPerformed
        // TODO add your handling code here:
        screenText += 4;
        displayResult.setText(screenText);
    }//GEN-LAST:event_buttonFourActionPerformed

    private void buttonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOneActionPerformed
        // TODO add your handling code here:
        screenText += 1;
        displayResult.setText(screenText);
    }//GEN-LAST:event_buttonOneActionPerformed

    private void opOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opOutputActionPerformed
        // TODO add your handling code here:
        String postFixExpression = infixToPostFix();
//        displayResult.setText(screenText);
//        displayResult.setText(postFixExpression);

//        displayResult.setText(postEvaluator("65/6*"));
        displayResult.setText(postEvaluator(postFixExpression));
        screenText = "";
        
    }//GEN-LAST:event_opOutputActionPerformed

    private void buttonFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFiveActionPerformed
        // TODO add your handling code here:
        screenText += 5;
        displayResult.setText(screenText);
    }//GEN-LAST:event_buttonFiveActionPerformed

    private void buttonSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSixActionPerformed
        // TODO add your handling code here:
        screenText += 6;
        displayResult.setText(screenText);
    }//GEN-LAST:event_buttonSixActionPerformed

    private void buttonThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThreeActionPerformed
        // TODO add your handling code here:
        screenText += 3;
        displayResult.setText(screenText);
    }//GEN-LAST:event_buttonThreeActionPerformed

    private void opSubstractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opSubstractActionPerformed
        // TODO add your handling code here:
        screenText += "-";
        displayResult.setText(screenText);
    }//GEN-LAST:event_opSubstractActionPerformed

    private void buttonSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSevenActionPerformed
        // TODO add your handling code here:
        screenText += 7;
        displayResult.setText(screenText);
    }//GEN-LAST:event_buttonSevenActionPerformed

    private void displayResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayResultActionPerformed
        // TODO add your handling code here:
//        screenText = "";
        
    }//GEN-LAST:event_displayResultActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        screenText = "";
        displayResult.setText(screenText);
        
    }//GEN-LAST:event_clearActionPerformed

    private void buttonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTwoActionPerformed
        // TODO add your handling code here:
        screenText += 2;
        displayResult.setText(screenText);
    }//GEN-LAST:event_buttonTwoActionPerformed

    private void buttonNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNineActionPerformed
        // TODO add your handling code here:
        screenText += 9;
        displayResult.setText(screenText);
    }//GEN-LAST:event_buttonNineActionPerformed

    private void opMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opMultiplyActionPerformed
        // TODO add your handling code here:
        screenText += "*";
        displayResult.setText(screenText);
    }//GEN-LAST:event_opMultiplyActionPerformed

    private void opAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opAddActionPerformed
        // TODO add your handling code here:
        screenText += "+";
        displayResult.setText(screenText);
    }//GEN-LAST:event_opAddActionPerformed

    private void opPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opPowerActionPerformed
        // TODO add your handling code here:
        screenText += "^";
        displayResult.setText(screenText);
    }//GEN-LAST:event_opPowerActionPerformed

    private void buttonZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonZeroActionPerformed
        // TODO add your handling code here:
        screenText += 0;
        displayResult.setText(screenText);
    }//GEN-LAST:event_buttonZeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesignCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesignCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesignCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesignCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesignCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEight;
    private javax.swing.JButton buttonFive;
    private javax.swing.JButton buttonFour;
    private javax.swing.JButton buttonNine;
    private javax.swing.JButton buttonOne;
    private javax.swing.JButton buttonSeven;
    private javax.swing.JButton buttonSix;
    private javax.swing.JButton buttonThree;
    private javax.swing.JButton buttonTwo;
    private javax.swing.JButton buttonZero;
    private javax.swing.JButton clear;
    private javax.swing.JTextField displayResult;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton opAdd;
    private javax.swing.JButton opDivide;
    private javax.swing.JButton opMultiply;
    private javax.swing.JButton opOutput;
    private javax.swing.JButton opPower;
    private javax.swing.JButton opSubstract;
    // End of variables declaration//GEN-END:variables
    private String screenText = "";
    
    // Infix to postFix
    String infixToPostFix() {
        String postFix = "";
        char[] operators = new char[50];
        int index = 0;
        for(int i = 0; i < screenText.length(); i++) {
            char ch = screenText.charAt(i);
            if(ch >= '0' && ch <= '9') {
                postFix += ch;
            } else  {
                while(index > 0 && precedence(ch) <= precedence(operators[index - 1])) {
                    postFix += operators[--index];
                }
                operators[index++] = ch;
            }
        }
        
        while(index > 0) {
            postFix += operators[--index];
        }
        
        return postFix;
    }
    
    String postEvaluator(String post) {
        String[] ch = new String[50];
        // ch[0] = "";
        int index = 0;
        for(int i = 0; i < post.length(); i++) {
            char op = post.charAt(i);
            if(op >= '0' && op <= '9') {
                ch[index++] = op + "";
            } else {
                int op2 = Integer.parseInt(ch[--index]);
                int op1 = Integer.parseInt(ch[--index]);
                int result = 0;
                if(op == '*') result = op2*op1;
                else if(op == '/') result = op1/op2;
                else if(op == '-') result = op1-op2;
                else if(op == '+') result = op1+op2;
                else if(op == '^') result = (int) Math.pow(op1, op2);
                
                ch[index++] = result+"";
            }
        }
        return ch[index-1];
    }
    
    int precedence(char op) {
        if(op == '^') return 3;
        else if (op == '/' || op == '*') return 2;
        else if(op == '+' || op == '-') return 1;
        else return 0;
    }
    
    
    
}
